# Generated by Django 4.2.6 on 2023-10-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review_product_quantity_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product_images/', upload_to='product_images/'),
        ),
    ]
