# Generated by Django 4.2.6 on 2023-10-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_cartitem_is_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fullname',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='mail',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
