# Generated by Django 4.2.6 on 2023-10-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_profile_fullname_profile_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fullname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mail',
            field=models.CharField(default='', max_length=100),
        ),
    ]
