# Generated by Django 4.2.6 on 2023-10-15 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
    ]
